bellsoft-21.0.9+15.tar.gz:
  size: 231042429
  object_id: 529d3b81-6d5e-4e39-7441-b1247afd6610
  sha: sha256:0fce26c223d01f06f879cc6674337dbeae06b263189e503d73098b5a342c20f3
luna-hsm-client-7.4/luna-hsm-client-7.4.tar:
  size: 40878080
  object_id: 41340dab-409e-4ee6-7571-2f88d38d89b4
  sha: sha256:7df1df90738778437a545ca2b0fb1427ab302503791d329946ab36edd5f07ec4
