luna-hsm-client-7.3/luna-hsm-client-7.3.tgz:
  size: 21694791
  object_id: d99d3677-9d0b-435d-7572-4fe7f4c3ed53
  sha: c56a24cf026d2cb15983b54d4120f4ba10faf87c
openjdk_1.8.0/openjdk-1.8.0_192.tar.gz:
  size: 45305426
  object_id: c2c75d99-be9f-43a2-794a-2e2c1c994fba
  sha: dae286f0e11c1a401e2c84a371f5cc2c6e2637ef
openjdk_1.8/openjdk-1.8.0_202.tar.gz:
  size: 103343856
  object_id: 877d2f1f-718f-4a6d-7ea1-fee443d114d6
  sha: 8ae76b80ffd1be54f43cf3490e6e1a871fc88e8e
openjdk_11/openjdk-11.0.2_07.tar.gz:
  size: 193740656
  object_id: a6d7db80-6b17-42d6-62d0-7aecd0fdd499
  sha: e2f09de1f2eb958c8b0f6ba1fdbf82d53936d707
