luna-hsm-client-7.4/luna-hsm-client-7.4.tar:
  size: 40878080
  object_id: 41340dab-409e-4ee6-7571-2f88d38d89b4
  sha: sha256:7df1df90738778437a545ca2b0fb1427ab302503791d329946ab36edd5f07ec4
openjdk_21.0/bellsoft-jre21.0.9+15-linux-amd64.tar.gz:
  size: 65877462
  object_id: d04c9d5f-16bd-4270-6df1-1f87bf9f40e4
  sha: sha256:0c9cb6693a9eab34e5990d581f9865824b159d365733960ccfa0e7eac9387b99
