lunaclient_5.3.0-11/lunaclient_5.3.0-11.tar.gz:
  size: 7306782
  object_id: 2ceaec43-ce10-43d8-92c3-a06654b6f3c7
  sha: 09f0136a78ecbf7cbfe78d78419ab6b8ff5891cb
openjdk_1.8.0/openjdk-1.8.0_192.tar.gz:
  size: 45305426
  object_id: c2c75d99-be9f-43a2-794a-2e2c1c994fba
  sha: dae286f0e11c1a401e2c84a371f5cc2c6e2637ef
openjdk_1.8/openjdk-1.8.0_202.tar.gz:
  size: 103343856
  object_id: dd345634-3c33-445b-6810-dab873875a16
  sha: 8ae76b80ffd1be54f43cf3490e6e1a871fc88e8e
openjdk_1.8/openjdk-jdk-1.8.0_202-trusty.tar.gz:
  size: 103341554
  object_id: bdbcf211-ffc0-41bc-432a-fbda2245d88e
  sha: 4d10c9e2605d0bd63dfe0155122379b66ad9f21d
openjdk_1.8/openjdk-jdk-1.8.0_212-trusty.tar.gz:
  size: 103369989
  object_id: 44ca1732-8326-4429-5084-2ef745588b99
  sha: cc2ded18b5bf61cae5796e3367c498ffcc5d6a3b
